/*
 * MathMe is an educational program created by Jesse Bannon for 
 * TCSS 305 at University of Washington Tacoma (Fall Quarter 2014). 
 *
 * It is open source and can be modified, changed, and used in
 * any way so long as Jesse Bannon and MathMe is referenced.
 */
package gui;

import class_resources.GetImage;
import class_resources.PlaySound;
import static games.FlashMath_Difficulty.EASY;
import static games.FlashMath_Difficulty.EXPERT;
import static games.FlashMath_Difficulty.HARD;
import static games.FlashMath_Difficulty.MEDIUM;
import games.FlashMath_Main;
import java.awt.event.KeyEvent;


/**
 * @author Jesse Bannon
 * @version 1.0
 * 
 * Flash Math graphical user interface.
 */
public class GUI_FlashMath extends javax.swing.JFrame {
    
    /** Status of GUI_FlashMath if it is open or not. */
    private static boolean IS_OPEN = false;
    
    private final FlashMath_Main flashMath;
    
    
    /**
     * Creates new form Exponents_GUI
     */
    public GUI_FlashMath() {
        initComponents();
        flashMath = new FlashMath_Main();  
        initStart();
        updateLabels();
    }
    
    public static boolean isOpen() {
        return IS_OPEN;
    }
    
    private void initStart() {
        flashMath.setTimerLabel(TimeLabel);
        flashMath.setQuestionLabel(QuestionLabel);
        
        flashMath.addSubjectCheckBoxItem(ArithmeticCheckBox);
        flashMath.addSubjectCheckBoxItem(MultiplicationCheckBox);
        flashMath.addSubjectCheckBoxItem(ExponentsCheckBox);
        flashMath.addSubjectCheckBoxItem(BinaryCheckBox);
        flashMath.addSubjectCheckBoxItem(ToBinaryCheckBox);    
    }
    
    private void updateLabels() {
        DifficultyButtonGroup.clearSelection();
        
        switch(flashMath.getDifficulty()) {
            case EASY:
                EasyButton.setSelected(true);
                break;
            case MEDIUM:
                MediumButton.setSelected(true);
                break;
            case HARD:
                HardButton.setSelected(true);
                break;
            case EXPERT:
                ExpertButton.setSelected(true);
                break;
            default:
                System.err.println("ERROR: INVALID DIFFICULTY");
                break;
        }
        
        ScoreLabel.setText(flashMath.getScoreLabelText());
        LivesLabel.setText(flashMath.getLivesLabelText());
        QuestionLabel.setText(flashMath.getQuestionLabelText());
        SubmitButton.setText(flashMath.getSubmitButtonText());
        
        AnswerTextField.setText(flashMath.getInputTextFieldString());
        AnswerTextField.setEditable(flashMath.getInputTextFieldEditable());  
    }
    
    private void setAnswerText() {
        flashMath.setInputTextFieldString(AnswerTextField.getText().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DifficultyButtonGroup = new javax.swing.ButtonGroup();
        FlashMathGamePanel = new javax.swing.JPanel();
        QuestionLabel = new javax.swing.JLabel();
        PlayerStatPanel = new javax.swing.JPanel();
        ScoreLabel = new javax.swing.JLabel();
        LivesLabel = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();
        AnswerTextField = new javax.swing.JTextField();
        SubmitPanel = new javax.swing.JPanel();
        InnerGridSubmitPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SubjectMenu = new javax.swing.JMenu();
        ArithmeticCheckBox = new javax.swing.JCheckBoxMenuItem();
        MultiplicationCheckBox = new javax.swing.JCheckBoxMenuItem();
        ExponentsCheckBox = new javax.swing.JCheckBoxMenuItem();
        BinaryCheckBox = new javax.swing.JCheckBoxMenuItem();
        ToBinaryCheckBox = new javax.swing.JCheckBoxMenuItem();
        DifficultyMenu = new javax.swing.JMenu();
        EasyButton = new javax.swing.JRadioButtonMenuItem();
        MediumButton = new javax.swing.JRadioButtonMenuItem();
        HardButton = new javax.swing.JRadioButtonMenuItem();
        ExpertButton = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flash Math");
        setIconImage(GetImage.returnImage("MATHME_ICON.png"));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        QuestionLabel.setBackground(new java.awt.Color(255, 255, 255));
        QuestionLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        QuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuestionLabel.setText("Problem");
        QuestionLabel.setPreferredSize(new java.awt.Dimension(338, 160));
        QuestionLabel.setRequestFocusEnabled(false);

        PlayerStatPanel.setLayout(new java.awt.GridLayout(1, 0));

        ScoreLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ScoreLabel.setText("Score");
        ScoreLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        PlayerStatPanel.add(ScoreLabel);

        LivesLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        LivesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LivesLabel.setText("Lives");
        LivesLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        PlayerStatPanel.add(LivesLabel);

        InputPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        TimeLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        TimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLabel.setText("Time");
        TimeLabel.setPreferredSize(new java.awt.Dimension(78, 31));
        InputPanel.add(TimeLabel);

        AnswerTextField.setPreferredSize(new java.awt.Dimension(120, 30));
        AnswerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnswerTextFieldKeyPressed(evt);
            }
        });
        InputPanel.add(AnswerTextField);

        SubmitPanel.setPreferredSize(new java.awt.Dimension(78, 28));
        SubmitPanel.setLayout(new java.awt.CardLayout());

        InnerGridSubmitPanel.setLayout(new java.awt.GridLayout(1, 0));

        SubmitButton.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        InnerGridSubmitPanel.add(SubmitButton);

        SubmitPanel.add(InnerGridSubmitPanel, "card2");

        InputPanel.add(SubmitPanel);

        javax.swing.GroupLayout FlashMathGamePanelLayout = new javax.swing.GroupLayout(FlashMathGamePanel);
        FlashMathGamePanel.setLayout(FlashMathGamePanelLayout);
        FlashMathGamePanelLayout.setHorizontalGroup(
            FlashMathGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlashMathGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FlashMathGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlayerStatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuestionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addContainerGap())
        );
        FlashMathGamePanelLayout.setVerticalGroup(
            FlashMathGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlashMathGamePanelLayout.createSequentialGroup()
                .addComponent(PlayerStatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(FlashMathGamePanel, "card3");

        jMenu1.setText("File");
        MenuBar.add(jMenu1);

        SubjectMenu.setText("Subject");

        ArithmeticCheckBox.setSelected(true);
        ArithmeticCheckBox.setText("Arithmetic");
        SubjectMenu.add(ArithmeticCheckBox);

        MultiplicationCheckBox.setText("Multiplication");
        SubjectMenu.add(MultiplicationCheckBox);

        ExponentsCheckBox.setText("Exponents");
        SubjectMenu.add(ExponentsCheckBox);

        BinaryCheckBox.setText("Binary");
        SubjectMenu.add(BinaryCheckBox);

        ToBinaryCheckBox.setText("To Binary");
        SubjectMenu.add(ToBinaryCheckBox);

        MenuBar.add(SubjectMenu);

        DifficultyMenu.setText("Difficulty");

        DifficultyButtonGroup.add(EasyButton);
        EasyButton.setText("Easy");
        EasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyButtonActionPerformed(evt);
            }
        });
        DifficultyMenu.add(EasyButton);

        DifficultyButtonGroup.add(MediumButton);
        MediumButton.setText("Medium");
        MediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumButtonActionPerformed(evt);
            }
        });
        DifficultyMenu.add(MediumButton);

        DifficultyButtonGroup.add(HardButton);
        HardButton.setText("Hard");
        HardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardButtonActionPerformed(evt);
            }
        });
        DifficultyMenu.add(HardButton);

        DifficultyButtonGroup.add(ExpertButton);
        ExpertButton.setText("Expert");
        ExpertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertButtonActionPerformed(evt);
            }
        });
        DifficultyMenu.add(ExpertButton);

        MenuBar.add(DifficultyMenu);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        setAnswerText();
        flashMath.submitButtonAction();
        updateLabels();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void AnswerTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnswerTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
            SubmitButton.doClick();       
    }//GEN-LAST:event_AnswerTextFieldKeyPressed

    private void EasyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyButtonActionPerformed
        flashMath.setDifficulty(EASY);
    }//GEN-LAST:event_EasyButtonActionPerformed

    private void MediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumButtonActionPerformed
        flashMath.setDifficulty(MEDIUM);
    }//GEN-LAST:event_MediumButtonActionPerformed

    private void HardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardButtonActionPerformed
        flashMath.setDifficulty(HARD);
    }//GEN-LAST:event_HardButtonActionPerformed

    private void ExpertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertButtonActionPerformed
        flashMath.setDifficulty(EXPERT);
    }//GEN-LAST:event_ExpertButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        IS_OPEN = true;
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        IS_OPEN = false;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        flashMath.closeGame();
        PlaySound.stop();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_FlashMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_FlashMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_FlashMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_FlashMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_FlashMath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerTextField;
    private javax.swing.JCheckBoxMenuItem ArithmeticCheckBox;
    private javax.swing.JCheckBoxMenuItem BinaryCheckBox;
    private javax.swing.ButtonGroup DifficultyButtonGroup;
    private javax.swing.JMenu DifficultyMenu;
    private javax.swing.JRadioButtonMenuItem EasyButton;
    private javax.swing.JRadioButtonMenuItem ExpertButton;
    private javax.swing.JCheckBoxMenuItem ExponentsCheckBox;
    private javax.swing.JPanel FlashMathGamePanel;
    private javax.swing.JRadioButtonMenuItem HardButton;
    private javax.swing.JPanel InnerGridSubmitPanel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel LivesLabel;
    private javax.swing.JRadioButtonMenuItem MediumButton;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JCheckBoxMenuItem MultiplicationCheckBox;
    private javax.swing.JPanel PlayerStatPanel;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JMenu SubjectMenu;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel SubmitPanel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JCheckBoxMenuItem ToBinaryCheckBox;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
